// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sol/Causality contributors.

/* embedded_font.h - Roboto Mono Nerd Font Mono embedded data.
   Generated by tools/embed_font.py from the Nerd Fonts Roboto Mono package.
   Regular and bold slots embed their matching Roboto Mono faces so UI text
   weight remains deterministic across platforms. */
#pragma once

extern const unsigned int  ca_embedded_font_size;
extern const unsigned char ca_embedded_font_data[];

extern const unsigned int  ca_embedded_font_bold_size;
extern const unsigned char ca_embedded_font_bold_data[];
