// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sol/Causality contributors.

/* embedded_font.h — Departure Mono Nerd Font (OFL-1.1) embedded data.
   Generated by tools/embed_font.py from upstream nerd-fonts release.
   Both regular and bold slots resolve to the same Regular face because
   Departure Mono only ships a Regular weight; widgets that want bold
   contrast should rely on size/colour instead. */
#pragma once

extern const unsigned int  ca_embedded_font_size;
extern const unsigned char ca_embedded_font_data[];

extern const unsigned int  ca_embedded_font_bold_size;
extern const unsigned char ca_embedded_font_bold_data[];
