#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Causality contributors.
#
# embed_font.py - convert a TTF/OTF into a C byte array consumed by
# causality's renderer.
#
# Usage: python3 tools/embed_font.py <input.ttf|otf> <symbol> <out.c>
#
# Emits a file with two definitions:
#     const unsigned int  <symbol>_size;
#     const unsigned char <symbol>_data[];
#
# The matching extern declarations live in renderer/embedded_font.h.

import sys
from pathlib import Path

HEADER = """\
// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Causality contributors.
//
// AUTOGENERATED by tools/embed_font.py - DO NOT EDIT.
//
// Source font: {source}
// License:     See vendors/causality/NOTICE.

#include "embedded_font.h"

const unsigned int {symbol}_size = {size}u;

const unsigned char {symbol}_data[] = {{
"""

FOOTER = "};\n"


def main():
    """Embed a binary font file as C source.

    Parameters:
        Reads argv as <input.ttf|otf> <symbol> <out.c>.
    """
    if len(sys.argv) != 4:
        print("usage: embed_font.py <input> <symbol> <out.c>", file=sys.stderr)
        sys.exit(2)

    src = Path(sys.argv[1])
    symbol = sys.argv[2]
    out = Path(sys.argv[3])
    data = src.read_bytes()

    lines = [HEADER.format(source=src.name, symbol=symbol, size=len(data))]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",\n")
    lines.append(FOOTER)

    out.write_text("".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {out} ({len(data)} bytes -> {out.stat().st_size} bytes C source)")


if __name__ == "__main__":
    main()
