#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Causality contributors.
#
# gen_unicode_width.py - generate the codepoint cell-width tables consumed by
# ca_codepoint_cell_width() (src/core/ca_unicode_width.c).
#
# Usage:
#   python3 tools/gen_unicode_width.py <UnicodeData.txt> <EastAsianWidth.txt> \
#       causality/src/core/ca_unicode_width_table.h
#
# Inputs are the Unicode Character Database files of one release, from
# https://www.unicode.org/Public/UCD/latest/ucd/.
#
# Width rules (the conventions of wcwidth(3) as implemented by modern
# terminal emulators):
#   0  General_Category Mn, Me, Cf, Cc (except U+00AD SOFT HYPHEN), plus the
#      conjoining Hangul medial/final jamo U+1160..U+11FF and U+D7B0..U+D7FF.
#   2  East_Asian_Width W or F, plus the ranges UAX #11 defaults to W when
#      unassigned (CJK ideograph blocks and planes 2/3).
#   1  everything else.
# Width 0 takes precedence over width 2.

import re
import sys
from pathlib import Path

HEADER = """\
// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Causality contributors.
//
// AUTOGENERATED by tools/gen_unicode_width.py - DO NOT EDIT.
//
// Source: {source}

#pragma once

#include <stdint.h>

typedef struct Ca_UnicodeRange {{
    uint32_t first;
    uint32_t last;
}} Ca_UnicodeRange;

"""

UNASSIGNED_WIDE = [
    (0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFAFF),
    (0x20000, 0x2FFFD), (0x30000, 0x3FFFD),
]

ZERO_CATEGORIES = {"Mn", "Me", "Cf", "Cc"}


def parse_unicode_data(path):
    """Return the set of zero-width codepoints from UnicodeData.txt."""
    zero = set()
    range_start = None
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        fields = line.split(";")
        if len(fields) < 3:
            continue
        cp = int(fields[0], 16)
        name, category = fields[1], fields[2]
        if name.endswith(", First>"):
            range_start = cp
            continue
        first = range_start if name.endswith(", Last>") else cp
        range_start = None
        if category in ZERO_CATEGORIES:
            zero.update(range(first, cp + 1))
    zero.discard(0x00AD)
    zero.update(range(0x1160, 0x1200))
    zero.update(range(0xD7B0, 0xD800))
    return zero


def parse_east_asian_width(path):
    """Return (wide codepoint set, version string) from EastAsianWidth.txt."""
    wide = set()
    version = "unknown"
    pattern = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)")
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if line.startswith("# EastAsianWidth-"):
            version = line[2:].strip()
        match = pattern.match(line)
        if not match:
            continue
        first = int(match.group(1), 16)
        last = int(match.group(2), 16) if match.group(2) else first
        if match.group(3) in ("W", "F"):
            wide.update(range(first, last + 1))
    for first, last in UNASSIGNED_WIDE:
        wide.update(range(first, last + 1))
    return wide, version


def to_ranges(codepoints):
    """Collapse a codepoint set into sorted inclusive (first, last) ranges."""
    ranges = []
    for cp in sorted(codepoints):
        if ranges and ranges[-1][1] == cp - 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return ranges


def emit_table(name, ranges):
    """Render one range table as C source."""
    rows = ",\n".join(f"    {{ 0x{a:05X}u, 0x{b:05X}u }}" for a, b in ranges)
    return f"static const Ca_UnicodeRange {name}[] = {{\n{rows}\n}};\n\n"


def main():
    """Generate the width table header from the two UCD source files."""
    if len(sys.argv) != 4:
        sys.exit("usage: gen_unicode_width.py <UnicodeData.txt> "
                 "<EastAsianWidth.txt> <out.h>")
    zero = parse_unicode_data(sys.argv[1])
    wide, version = parse_east_asian_width(sys.argv[2])
    wide -= zero
    out = HEADER.format(source=version)
    out += emit_table("ca_unicode_zero_width", to_ranges(zero))
    out += emit_table("ca_unicode_double_width", to_ranges(wide))
    Path(sys.argv[3]).write_text(out, encoding="utf-8")


if __name__ == "__main__":
    main()
